global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pinger'
    scrape_interval: 2s
    scrape_timeout: 2s
    static_configs:
    - targets: ['pinger:8080']
  - job_name: 'speedtest'
    scrape_interval: 15m
    scrape_timeout: 3m
    static_configs:
    - targets: ['prometheusspeedtest:9516']
